Milestone 1
hassaan-ahmed-brainx/election-dapp pull request #2
Opened 2023-03-28 08:42 UTC by hassaan-ahmed-brainx

- Add Candidate
- Cast a Vote
- Election Contract
- Test cases

2023-03-28 09:20 UTC, ali-iqbal-brainx commented on src/components/Addcandidate.jsx
> +    let [Address_candidate, setAddress_candidate] = useState(localStorage.getItem('candidate_address') || '');
use camelCase notation for variable names

2023-03-28 09:23 UTC, ali-iqbal-brainx commented on src/components/Castvote.jsx
> +    let ContractAddress = '0xf873BAfd52D35d78dbA73C3d54f1bDDa2f3660b3';
declare constants in a separate file and then import and use them

2023-03-28 09:25 UTC, ali-iqbal-brainx commented on test/tests.js
> +    await contract.addCandidate("0x8921a2034Efdb48BcD1cF2aEbD49aB3a9D7448C8", "Candidate1");
add them in separate constant file and then import and use them

2023-03-28 09:26 UTC, ali-iqbal-brainx requested changes
-use camelCase notation for variable names
-use const for values that are for read only purpose
-declare constants in a separate file and then import and use them

2023-03-31 09:53 UTC, ali-faiz-brainx commented on src/components/Addcandidate.jsx
> +    let { handleAddCandidate } = candidatesData;
Add variable assignment things in state instead of a global variables

2023-03-31 09:53 UTC, ali-faiz-brainx commented on src/components/Castvote.jsx
> +	const contractAddress = Constants.contractAddress
Manage web3 content using states instead of global vairbales

2023-03-31 09:59 UTC, closed without merging